
POST http://localhost:3000/auth/sign-up
Content-type: application/json

{
    "email": "dane@email.com",
    "password": "1234567a"
}

###
POST http://localhost:3000/auth/sign-in
Content-type: application/json

{
    "email": "dan@email.com",
    "password": "12345678"
}

###
POST http://localhost:3000/auth/refresh-token
Content-type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MjAyMDM4NDYsImV4cCI6MTcyMjc5NTg0Niwic3ViIjoiYmJkYzk4Y2QtZjhmMC00ZDJiLWEzZGQtZDhjMjBkNzc5MDE1In0.Rvq8RKW4CnY_7CtkSRfez6jBqmXqJhdqKxgqYoSImWA"
}

### 
POST http://localhost:3000/chat/channels
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiYmJkYzk4Y2QtZjhmMC00ZDJiLWEzZGQtZDhjMjBkNzc5MDE1IiwibmFtZSI6InRlc3RlIiwiZW1haWwiOiJ0ZXN0ZWphQGVtYWlsLmNvbSIsImNoYW5uZWxzIjpbXX0sImlhdCI6MTcyMDIwMzg0NiwiZXhwIjoxNzIwMjA0MDI2LCJzdWIiOiJiYmRjOThjZC1mOGYwLTRkMmItYTNkZC1kOGMyMGQ3NzkwMTUifQ.oBuSHxtNqdM3aKAUPIU1ABSu3TCpQWRrg1vnfWQL_kE

{
    "type": "direct",
    "name": "Hello World",
    "members": [
        "testeja@email.com",
        "teste@email.com"
    ]
}

### 
POST http://localhost:3000/chat/channels
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiYmJkYzk4Y2QtZjhmMC00ZDJiLWEzZGQtZDhjMjBkNzc5MDE1IiwibmFtZSI6InRlc3RlIiwiZW1haWwiOiJ0ZXN0ZWphQGVtYWlsLmNvbSIsImNoYW5uZWxzIjpbXX0sImlhdCI6MTcyMDIwMzg0NiwiZXhwIjoxNzIwMjA0MDI2LCJzdWIiOiJiYmRjOThjZC1mOGYwLTRkMmItYTNkZC1kOGMyMGQ3NzkwMTUifQ.oBuSHxtNqdM3aKAUPIU1ABSu3TCpQWRrg1vnfWQL_kE

{
    "type": "group",
    "name": "Teste 2",
    "members": [
        "teste@email.com",
        "testeja@email.com"
    ]
}
### 
DELETE http://localhost:3000/chat/channels
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiY2JiM2ZlMjQtYmNiNS00ODI3LThiOTAtZGU5MjBjMjQ2YWZkIiwibmFtZSI6InRlc3RlIiwiZW1haWwiOiJ0ZXN0ZUBlbWFpbC5jb20iLCJjaGFubmVscyI6W119LCJpYXQiOjE3MTQxNTM4NDcsImV4cCI6MTcxNDE1NDAyNywic3ViIjoiY2JiM2ZlMjQtYmNiNS00ODI3LThiOTAtZGU5MjBjMjQ2YWZkIn0.eA_EtHvUVikV02DnexxujNpH4DnKA3plIe43-1YgVNY

{
    "id": "6551ae1f-d22c-4ac2-b1da-a8e1a1eab191"
}
### 
PUT http://localhost:3000/chat/channels
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiY2JiM2ZlMjQtYmNiNS00ODI3LThiOTAtZGU5MjBjMjQ2YWZkIiwibmFtZSI6InRlc3RlIiwiZW1haWwiOiJ0ZXN0ZUBlbWFpbC5jb20iLCJjaGFubmVscyI6W119LCJpYXQiOjE3MTQxNTcwNTcsImV4cCI6MTcxNDE1NzIzNywic3ViIjoiY2JiM2ZlMjQtYmNiNS00ODI3LThiOTAtZGU5MjBjMjQ2YWZkIn0.NotlwJeKBn4Ir4gSRetWiKFK0L_WIiwMAbmqZs3Ic1A

{
    "id": "81704cac-9d6d-4d23-8b9b-56a48e45d1df",
    "name": "Hello World 2",
    "members": [
        "testjje@email.com",
        "teste@email.com"
    ]
}

###
GET http://localhost:3000/chat/channels/81704cac-9d6d-4d23-8b9b-56a48e45d1df
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiYmJkYzk4Y2QtZjhmMC00ZDJiLWEzZGQtZDhjMjBkNzc5MDE1IiwibmFtZSI6InRlc3RlIiwiZW1haWwiOiJ0ZXN0ZWphQGVtYWlsLmNvbSIsImNoYW5uZWxzIjpbXX0sImlhdCI6MTcyNTI5MDM4NywiZXhwIjoxNzI1MjkwNTY3LCJzdWIiOiJiYmRjOThjZC1mOGYwLTRkMmItYTNkZC1kOGMyMGQ3NzkwMTUifQ.9uQ8xbaJ8zpageBsX2FfsjgsbWs_IjKtDoOyoVSN2wI